# -*- coding: utf-8 -*-
"""nordik_seguros_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDB2wmZbY_YEaujb9Uc-DPF3OGcBp8dr
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

class DataPipeline:
    def __init__(self):
        self.scaler = StandardScaler()
        self.kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
        self.vars_to_scale = None
        self.log_transform_vars = [
            'Productos_Vida', 'Productos_Vehiculos', 'Productos_Otros',
            'Gasto_Vida', 'Gasto_Vehiculos', 'Gasto_Otros'
        ]
        self.cols_to_drop = [
            'Ingresos_Mas_De_40000', 'Educacion_Superior', 'Poblacion_Empresario',
            'Tipo_Soltero', 'Medico_Seguridad_Social', 'Vivienda_Alquiler',
            'Fecha_Nacimiento', 'Fecha_Alta', 'ID_Cliente', 'ID_Zona'
        ]

    def _transform_features(self, df):
        data = df.copy()
        # Fechas y Feature Engineering
        data['Fecha_Nacimiento'] = pd.to_datetime(data['Fecha_Nacimiento'], errors='coerce', dayfirst=True)
        data['Fecha_Alta'] = pd.to_datetime(data['Fecha_Alta'], errors='coerce', dayfirst=True)
        ref_date = pd.to_datetime("2025-01-01")
        data['Edad'] = (ref_date - data['Fecha_Nacimiento']).dt.days // 365
        data['Antiguedad'] = (ref_date - data['Fecha_Alta']).dt.days // 365
        data['Sexo'] = data['Sexo'].map({'Hombre': 0, 'Mujer': 1})
        return data.drop(columns=self.cols_to_drop, errors='ignore')

    def fit_transform(self, df):
        data = self._transform_features(df)
        for col in self.log_transform_vars:
            if col in data.columns: data[col] = np.log1p(data[col])
        self.vars_to_scale = data.columns.drop('Sexo')
        data[self.vars_to_scale] = self.scaler.fit_transform(data[self.vars_to_scale])
        self.kmeans.fit(data)
        return data

    def predict(self, df):
        data = self._transform_features(df)
        for col in self.log_transform_vars:
            if col in data.columns: data[col] = np.log1p(data[col])
        data[self.vars_to_scale] = self.scaler.transform(data[self.vars_to_scale])
        return self.kmeans.predict(data)